simple test

diff --git a/.github/workflows/deploy-broker.yml b/.github/workflows/deploy-broker.yml
--- a/.github/workflows/deploy-broker.yml
+++ b/.github/workflows/deploy-broker.yml
@@ -36,11 +36,28 @@ jobs:
         env:
           APP_URL: ${{ steps.prepare-step.outputs.app_url }}
         run: |
+          APP_URL=${APP_URL}/service/mongo/test3
           echo "working with "$APP_URL
-          curl -H "Content-Type: application/json" -X PUT -d '{"_class":"org.cloudfoundry.samples.music.domain.Album", "artist": "Tenno", "title": "Journey", "releaseYear": "2019", "genre": "chillhop" }' $APP_URL/albums
-          result=$(curl -X GET $APP_URL/albums -s | awk '/Tenno/{print "true"}')
-          echo $result
-          if [[ -z $result ]]; then
-            echo "FAILED. Curl check: Text is not found"
-            exit 1
+          #curl -H "Content-Type: application/json" -X PUT -d '{"_class":"org.cloudfoundry.samples.music.domain.Album", "artist": "Tenno", "title": "Journey", "releaseYear": "2019", "genre": "chillhop" }' $APP_URL/albums
+          status=$(curl -X PUT -d '{"data":"sometest130"}' ${APP_URL})
+          if [[ $status != "success" ]]; then
+              echo "Error: check application"
+              exit 1
           fi
+          result=$(echo $(curl -X GET ${APP_URL}))
+          if [ "${result}" = '{"data":"sometest130"}' ]; then
+              echo "Application is working"
+              echo "Cleaning data.."
+              curl -X DELETE ${APP_URL}
+          else
+              echo "GET ${APP_URL} finished with result: ${result}"
+              echo "FAILED. Application doesn't work"
+              exit 1
+          fi
+          # curl -X PUT -d '{"data":"sometest130"}' http://simple.apps.sanmarcos.cf-app.com/service/mongo/test3
+          # result=$(curl -X GET $APP_URL/albums -s | awk '/Tenno/{print "true"}')
+          # echo $result
+          # if [[ -z $result ]]; then
+          #   echo "FAILED. Curl check: Text is not found"
+          #   exit 1
+          # fi
