test output

diff --git a/.github/workflows/deploy-broker.yml b/.github/workflows/deploy-broker.yml
--- a/.github/workflows/deploy-broker.yml
+++ b/.github/workflows/deploy-broker.yml
@@ -21,6 +21,7 @@ jobs:
           pcf_password: ${{ secrets.PCF_PASSWORD }}
 
       - name: Create CF org, space, broker, service and push app)
+          id: prepare-step
         uses: ./.github/actions/prepare-cf
         with:
           pcf_url: ${{ secrets.PCF_URL }}
@@ -29,3 +30,17 @@ jobs:
           atlas_project_id: ${{ secrets.ATLAS_PROJECT_ID }}
           atlas_public_key: ${{ secrets.ATLAS_PUBLIC_KEY }}
           atlas_private_key: ${{ secrets.ATLAS_PRIVATE_KEY }}
+
+      - name: Check application. Add album
+        id: check-app
+        env:
+          APP_URL: ${{ steps.prepare-step.outputs.app_url }}
+        run: |
+          echo "working with "$APP_URL
+          curl -H "Content-Type: application/json" -X PUT -d '{"_class":"org.cloudfoundry.samples.music.domain.Album", "artist": "Tenno", "title": "Journey", "releaseYear": "2019", "genre": "chillhop" }' $APP_URL/albums
+          result=$(curl -X GET $APP_URL/albums -s | awk '/Tenno/{print "true"}')
+          echo $result
+          if [[ -z $result ]]; then
+            echo "FAILED. Curl check: Text is not found"
+            exit 1
+          fi
